/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as ConfiguracionesRouteImport } from './routes/configuraciones'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as TrabajosRouteImport } from './routes/trabajos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionesRoute = ConfiguracionesRouteImport.update({
  id: '/configuraciones',
  path: '/configuraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajosRoute = TrabajosRouteImport.update({
  id: '/trabajos',
  path: '/trabajos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/configuraciones': typeof ConfiguracionesRoute
  '/resultados': typeof ResultadosRoute
  '/trabajos': typeof TrabajosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/configuraciones': typeof ConfiguracionesRoute
  '/resultados': typeof ResultadosRoute
  '/trabajos': typeof TrabajosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/configuraciones': typeof ConfiguracionesRoute
  '/resultados': typeof ResultadosRoute
  '/trabajos': typeof TrabajosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ajustes' | '/configuraciones' | '/resultados' | '/trabajos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ajustes' | '/configuraciones' | '/resultados' | '/trabajos'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/configuraciones'
    | '/resultados'
    | '/trabajos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  ConfiguracionesRoute: typeof ConfiguracionesRoute
  ResultadosRoute: typeof ResultadosRoute
  TrabajosRoute: typeof TrabajosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuraciones': {
      id: '/configuraciones'
      path: '/configuraciones'
      fullPath: '/configuraciones'
      preLoaderRoute: typeof ConfiguracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabajos': {
      id: '/trabajos'
      path: '/trabajos'
      fullPath: '/trabajos'
      preLoaderRoute: typeof TrabajosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  ConfiguracionesRoute: ConfiguracionesRoute,
  ResultadosRoute: ResultadosRoute,
  TrabajosRoute: TrabajosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
